from engine.models import BuildableManufacturer, BuildableManufacturerName, Item, Recipe

items: dict[str, Item] = {}
recipes: dict[str, Recipe] = {}
production_buildings: dict[BuildableManufacturerName, BuildableManufacturer] = {
    BuildableManufacturerName.CONSTRUCTOR: BuildableManufacturer(
        building_name=BuildableManufacturerName.CONSTRUCTOR,
        display_name="Constructor",
        power_active=4,
        input_belts=1,
        output_belts=1,
        max_somersloops=1,
    ),
    BuildableManufacturerName.SMELTER: BuildableManufacturer(
        building_name=BuildableManufacturerName.SMELTER,
        display_name="Smelter",
        power_active=4,
        input_belts=1,
        output_belts=1,
        max_somersloops=1,
    ),
    BuildableManufacturerName.FOUNDRY: BuildableManufacturer(
        building_name=BuildableManufacturerName.FOUNDRY,
        display_name="Foundry",
        power_active=16,
        input_belts=2,
        output_belts=1,
        max_somersloops=2,
    ),
    BuildableManufacturerName.REFINERY: BuildableManufacturer(
        building_name=BuildableManufacturerName.REFINERY,
        display_name="Refinery",
        power_active=30,
        input_belts=1,
        output_belts=1,
        max_somersloops=2,
        input_pipes=1,
        output_pipes=1,
    ),
    BuildableManufacturerName.PACKAGER: BuildableManufacturer(
        building_name=BuildableManufacturerName.PACKAGER,
        display_name="Packager",
        power_active=10,
        input_belts=1,
        output_belts=1,
        max_somersloops=0,
        input_pipes=1,
        output_pipes=1,
    ),
    BuildableManufacturerName.MANUFACTURER: BuildableManufacturer(
        building_name=BuildableManufacturerName.MANUFACTURER,
        display_name="Manufacturer",
        power_active=55,
        input_belts=4,
        output_belts=1,
        max_somersloops=4,
    ),
    BuildableManufacturerName.ASSEMBLER: BuildableManufacturer(
        building_name=BuildableManufacturerName.ASSEMBLER,
        display_name="Assembler",
        power_active=15,
        input_belts=2,
        output_belts=1,
        max_somersloops=2,
    ),
    BuildableManufacturerName.BLENDER: BuildableManufacturer(
        building_name=BuildableManufacturerName.BLENDER,
        display_name="Blender",
        power_active=75,
        input_belts=2,
        output_belts=1,
        max_somersloops=4,
        input_pipes=2,
        output_pipes=1,
    ),
    BuildableManufacturerName.ACCELERATOR: BuildableManufacturer(
        building_name=BuildableManufacturerName.ACCELERATOR,
        display_name="Particle Accelerator",
        power_active=0,
        input_belts=2,
        input_pipes=1,
        output_belts=1,
        max_somersloops=4,
        variable_power=True,
    ),
    BuildableManufacturerName.CONVERTER: BuildableManufacturer(
        building_name=BuildableManufacturerName.CONVERTER,
        display_name="Converter",
        power_active=0,
        input_belts=2,
        output_belts=1,
        output_pipes=1,
        max_somersloops=2,
        variable_power=True,
    ),
    BuildableManufacturerName.ENCODER: BuildableManufacturer(
        building_name=BuildableManufacturerName.ENCODER,
        display_name="Quantum Encoder",
        power_active=0,
        input_belts=3,
        input_pipes=1,
        output_belts=1,
        output_pipes=1,
        max_somersloops=4,
        variable_power=True,
    ),
}
